portal:
  image: nginx
  ports:
   - "8080:80"
  volumes:
   - ./cluster/default.conf:/etc/nginx/conf.d/default.conf
  links:
   - tomcat1:tomcat1
   - tomcat2:tomcat2
   - tomcat3:tomcat3
tomcat1:
  image: tomcat
  volumes:
   - ./cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - ./cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - ./cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
  links:
   - mysql
tomcat2:
  image: tomcat
  volumes:
   - ./cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - ./cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - ./cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
  links:
   - mysql
tomcat3:
  image: tomcat
  volumes:
   - ./cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - ./cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - ./cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
  links:
   - mysql
mysql:
  image: mysql
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=nemanja
  - MYSQL_USER=hidmet
  - MYSQL_PASSWORD=hidmet
  volumes:
  - ./cluster/data:/var/lib/mysql
  ports:
    - "3306:3306"
